version: "3" # 도커 컴포즈 버전
services: # 실행하려는 컨테이너 정의
  react: # 컨테이너 이름
    build: # 현 디렉토리에 있는 도커파일 사용
      context: . # docker 이미지를 구성하기 위한 파일과 폴더들이 있는 위치
      dockerfile: Dockerfile.dev # 도커파일 명시
    ports:
      - "3000:3000" # 로컬:컨테이너 포트
    volumes:
      - /usr/src/app/node_modules # 참조하지 않을 것(로컬엔 삭제해주었으므로)
      - ./:/usr/src/app #로컬 머신에 있는 파일들 맵핌
    stdin_open: true # 리액트 앱 끌 때 필요(버그 fix)

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ["npm", "run", "test"]
